### ISSUE TITLE
导出模型的参数和步骤

### ISSUE THREAD

**Issue by DashBear** [YaoQ/yolov5-face-RK3588#2]
您好，能提供一下pt模型导出的onnx模型参数、以及onnx转换rknn模型的参数 和整体的步骤么？万分感谢！！

**Comment by YaoQ** [comment]
[Uploading yolov5n-face-onnx.zip…]()
这个是Yolov5，截取了detect层后的onnx文件

**Comment by YaoQ** [comment]
仓库中扩展了转rknn的脚本，以及导出的onnx文件，请参考
